onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - es5-ext
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract
  - sharp

publicHoistPattern:
  - file-loader
  - prop-types
