name: Performance Budget
on: [push]
jobs:
  budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: install & build
        run: |
          pnpm install
          pnpm run build
      - name: budget
        run: pnpm dlx bundlesize
